Add UDMA buffer pool and the "Share UDMA Buffer" property
MistySOM/gstreamer1.0-drpai pull request #45
Opened 2024-06-26 00:10 UTC by matinlotfali

TBD

2024-07-04 22:29 UTC, matinlotfali commented
Sadly stopped working :cry:

2024-07-08 17:47 UTC, mistyron commented
> Sadly stopped working 😢

Is there any follow up on this?

2024-07-08 18:06 UTC, matinlotfali commented
Should prioritize other stuff. Will get back on it later.

2024-07-24 17:58 UTC, mistyron requested changes
review: TBD (copied from the description of the PR) :)

2025-10-02 21:03 UTC, matinlotfali commented
It is now working. Updated the descriptions

2025-10-16 23:36 UTC, kieferMaland approved these changes
Reviewed at a high level and tested on SOM with and without showing fps and bboxes. 
LGTM.
Great work!

2025-10-17 15:00 UTC, merged